experiment:
  method: adacal
  architecture: lstm
  seed: 0
  dataset: ucr_forda
  description: 'Sensitivity: update_every=10'
training:
  epochs: 100
  batch_size: 64
  learning_rate: 0.001
method_params:
  update_every: 10
  eta: 0.05
  alpha:
  - 0.33
  - 0.33
  - 0.34
  sensitivity_param: update_every
  sensitivity_value: 10
